# Generated by Django 2.2.5 on 2019-09-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglogprofile', '0002_auto_20190904_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profimg',
            field=models.ImageField(default='images/about.jpg', upload_to='images/'),
        ),
    ]
